name: pmetrics
channels:
  - bioconda
  - conda-forge
  - r

dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - bwidget=1.9.14
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - cairo=1.14.12
  - curl=7.68.0
  - fontconfig=2.13.0
  - freetype=2.10.1
  - fribidi=1.0.9
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib=2.56.2
  - graphite2=1.3.13
  - gsl=2.4
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=1.9.0
  - icu=58.2
  - java-jdk=8.0.112
  - jpeg=9c
  - krb5=1.16.4
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.68.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.9
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - make=4.3
  - ncurses=6.1
  - openjdk=8.0.112
  - openssl=1.1.1f
  - pango=1.42.4
  - pcre=8.44
  - pixman=0.38.0
  - pthread-stubs=0.4
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.6
  - r-base=3.5.1
  - r-base64enc=0.1_3
  - r-callr=3.4.3
  - r-cli=2.0.2
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-curl=4.3
  - r-desc=1.2.0
  - r-devtools=1.13.6
  - r-digest=0.6.25
  - r-ellipsis=0.3.0
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-fastmap=1.0.1
  - r-foreach=1.5.0
  - r-git2r=0.23.0
  - r-glue=1.4.0
  - r-htmltools=0.4.0
  - r-httpuv=1.5.2
  - r-isoband=0.2.1
  - r-iterators=1.0.12
  - r-jsonlite=1.6.1
  - r-labeling=0.3
  - r-later=1.0.0
  - r-lattice=0.20_41
  - r-lifecycle=0.2.0
  - r-magrittr=1.5
  - r-mass=7.3_51.5
  - r-matrix=1.2_14
  - r-memoise=1.1.0
  - r-mgcv=1.8_31
  - r-munsell=0.5.0
  - r-nlme=3.1_147
  - r-openssl=1.4.1
  - r-pillar=1.4.3
  - r-pkgbuild=1.0.6
  - r-pkgconfig=2.0.3
  - r-pkgload=1.0.2
  - r-plogr=0.2.0
  - r-plyr=1.8.6
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.2
  - r-ps=1.3.2
  - r-purrr=0.3.3
  - r-r6=2.4.1
  - r-rcolorbrewer=1.1_2
  - r-rjson=0.2.20
  - r-rlang=0.4.5
  - r-rprojroot=1.3_2
  - r-rstudioapi=0.11
  - r-scales=1.1.0
  - r-sourcetools=0.1.7
  - r-sys=3.3
  - r-testthat=2.3.2
  - r-tibble=3.0.0
  - r-tidyselect=1.0.0
  - r-utf8=1.1.4
  - r-vctrs=0.2.4
  - r-viridislite=0.3.0
  - r-whisker=0.3_2
  - r-withr=2.1.2
  - r-xtable=1.8_4
  - r-zeallot=0.1.0
  - readline=7.0
  - tk=8.6.10
  - tktable=2.10
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - r-BH=1.72.0-3
  - r-chron=2.3-55
  - r-doParallel=1.0.15
  - r-dplyr=0.8.5
  - r-ggplot2=3.3.0
  - r-gtable=0.3.0
  - r-httr=1.4.1
  - r-mclust=5.4.6
  - r-mime=0.9
  - r-openxlsx=4.1.4
  - r-promises=1.1.0
  - r-Rcpp=1.0.4.6
  - r-shiny=1.4.0.2
  #- r-stringi=1.4.6
  - r-zip=2.0.4
  - r-tidyr=1.0.2

